from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class ServiceError(Exception):
    """
    Controlled JSON error for every endpoint of the authors microservice.
    Rendered by the handler registered in app.py as
    {"success": false, "code": ..., "message": ...} (same shape as the
    401/403/503 errors rendered by library_shared.flask_auth).
    """

    code: str
    message: str
    http_status: int = 400
    details: dict | None = field(default=None)

    def __str__(self) -> str:
        return f"{self.code}: {self.message}"


# --- 400 ---------------------------------------------------------------------

def invalid_input(message: str) -> ServiceError:
    return ServiceError("INVALID_INPUT", message, 400)


def invalid_body() -> ServiceError:
    return ServiceError("INVALID_INPUT", "Request body must be a JSON object.", 400)


def unknown_fields(names: list[str]) -> ServiceError:
    return ServiceError("UNKNOWN_FIELDS", "Request contains unknown fields.", 400, {"fields": names})


def fields_not_allowed(names: list[str]) -> ServiceError:
    # autor_id is a BIGSERIAL generated by PostgreSQL and comes from the URL.
    return ServiceError(
        "FIELDS_NOT_ALLOWED",
        "These fields are managed by the server and cannot be sent.",
        400,
        {"fields": names},
    )


# --- 404 ---------------------------------------------------------------------

def author_not_found() -> ServiceError:
    return ServiceError("AUTHOR_NOT_FOUND", "Author not found.", 404)


def book_not_found() -> ServiceError:
    return ServiceError("BOOK_NOT_FOUND", "Book not found.", 404)


def relation_not_found() -> ServiceError:
    return ServiceError("RELATION_NOT_FOUND", "The author is not associated with this book.", 404)


# --- 409 ---------------------------------------------------------------------

def relation_already_exists() -> ServiceError:
    return ServiceError("RELATION_ALREADY_EXISTS", "The author is already associated with this book.", 409)


def author_has_books(books_count: int) -> ServiceError:
    return ServiceError(
        "AUTHOR_HAS_BOOKS",
        "The author is associated with books; remove those associations first.",
        409,
        {"books_count": books_count},
    )


# --- 5xx ---------------------------------------------------------------------

def database_unavailable() -> ServiceError:
    return ServiceError("DATABASE_UNAVAILABLE", "Database temporarily unavailable.", 503)


def internal_error() -> ServiceError:
    return ServiceError(
        "INTERNAL_ERROR",
        "An internal error occurred while processing the request.",
        500,
    )
